 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb023.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb028.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb058.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb072.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb075.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb090.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb092.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb095.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb102.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb105.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb110.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb111.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb115.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb117.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb120.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb124.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb125.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb130.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb134.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb141.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb144.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb148.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb155.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb158.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb170.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb171.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb178.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb179.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb181.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb184.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb186.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb202.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb206.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb209.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb211.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb213.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb216.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb231.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb233.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb238.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb239.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb241.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb245.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb249.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb253.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb256.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb264.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb265.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb267.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb270.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb271.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb274.png --mode train ||
