 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb002.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb005.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb010.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb012.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb013.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb015.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb017.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb019.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb021.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb025.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb030.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb032.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb059.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb063.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb069.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb080.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb081.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb083.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb091.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb097.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb099.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb104.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb107.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb121.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb126.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb127.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb132.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb142.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb145.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb150.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb152.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb160.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb163.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb165.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb167.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb175.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb188.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb190.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb191.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb193.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb195.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb198.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb199.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb204.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb207.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb212.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb214.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb218.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb219.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb222.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb223.png --mode train ||
 python main_train.py --input_dir /home/radiomics/djl/SinGAN-master/Input/Images --input_name mdb226.png --mode train ||
